// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqCpfYcXGwRqxskFcPRoRVZsnQhgseaug',
    appId: '1:737735399868:web:64fe8ffc5d78fc5e8ff3b9',
    messagingSenderId: '737735399868',
    projectId: 'piggybet666',
    authDomain: 'piggybet666.firebaseapp.com',
    storageBucket: 'piggybet666.firebasestorage.app',
    measurementId: 'G-TLF1T7SS12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrzwXLk-VTGjseDm7a9hMmLpDhOb5sI9s',
    appId: '1:737735399868:android:e5bcd8e15432f00e8ff3b9',
    messagingSenderId: '737735399868',
    projectId: 'piggybet666',
    storageBucket: 'piggybet666.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATYrNSeLVQcjzlCNkJM0rVG_TaWFG9yoQ',
    appId: '1:737735399868:ios:169a0bd1c91314168ff3b9',
    messagingSenderId: '737735399868',
    projectId: 'piggybet666',
    storageBucket: 'piggybet666.firebasestorage.app',
    iosBundleId: 'com.example.piggybet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATYrNSeLVQcjzlCNkJM0rVG_TaWFG9yoQ',
    appId: '1:737735399868:ios:169a0bd1c91314168ff3b9',
    messagingSenderId: '737735399868',
    projectId: 'piggybet666',
    storageBucket: 'piggybet666.firebasestorage.app',
    iosBundleId: 'com.example.piggybet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqCpfYcXGwRqxskFcPRoRVZsnQhgseaug',
    appId: '1:737735399868:web:3b26b83b0ccfef048ff3b9',
    messagingSenderId: '737735399868',
    projectId: 'piggybet666',
    authDomain: 'piggybet666.firebaseapp.com',
    storageBucket: 'piggybet666.firebasestorage.app',
    measurementId: 'G-ES13V5CL9H',
  );
}
